Push container

diff --git a/.github/workflows/cp4i-image.yml b/.github/workflows/cp4i-image.yml
--- a/.github/workflows/cp4i-image.yml
+++ b/.github/workflows/cp4i-image.yml
@@ -87,17 +87,25 @@ jobs:
           cd /tmp && curl https://download.docker.com/linux/static/stable/x86_64/docker-27.1.1.tgz | tar -xzvf -
           mv /tmp/docker/docker /usr/bin/docker
 
-      - name: Login to cp.icr.io
-        uses: docker/login-action@v2
+      - name: Login to cp.icr.io (base images)
+        uses: docker/login-action@v3
         with:
           username: ${{ secrets.CP_USERNAME }}
           password: ${{ secrets.CP_PASSWORD }}
           registry: cp.icr.io
 
+      - name: Login to Docker Hub (destination)
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
       - name: Create container image
         run: |
           # checkout v4 does this and the removes it
           git config --global --add safe.directory $PWD
+
+          set -e # Fail on error
           
           export DATE=$(date '+%Y%m%d%H%M%S')
           export COMMIT=$(git log -1 --pretty=%h)
@@ -106,4 +114,12 @@ jobs:
           
           cd /tmp/build
           chmod -R 777 .
+          echo ========================================================================
+          echo Building container image
+          echo ========================================================================
           docker build --file Dockerfile --build-arg BASE_IMAGE=cp.icr.io/cp/appc/ace-server-prod:12.0.12.0-r1-20240417-022324 -t tdolby/experimental:tea-github-action-$TAG .
+          
+          echo ========================================================================
+          echo Pushing container image
+          echo ========================================================================
+          docker push tdolby/experimental:tea-github-action-$TAG .
