Docker image build

diff --git a/.github/workflows/cp4i-image.yml b/.github/workflows/cp4i-image.yml
--- a/.github/workflows/cp4i-image.yml
+++ b/.github/workflows/cp4i-image.yml
@@ -57,9 +57,36 @@ jobs:
           
       - name: Create the container structure
         run: |
+          set -e # Fail on error
           rm -rf /tmp/build
           mkdir -p /tmp/build
-          cp tekton/Dockerfile /tmp/build/Dockerfile
+          echo ========================================================================
+          echo Creating work directory structure
+          echo ========================================================================
+          mqsicreateworkdir /tmp/build/ace-server
+          mqsibar -w /tmp/build/ace-server -a $PWD/tea-application-combined.bar
+          ibmint optimize server --work-dir /tmp/build/ace-server
+                    
+          echo ========================================================================
+          echo Copy in various startup files
+          echo ========================================================================
+          cp $PWD/demo-infrastructure/TEAJDBC.policyxml /tmp/build/ace-server/
+          cp $PWD/demo-infrastructure/application-overrides.txt /tmp/build/ace-server/
+          cp $PWD/demo-infrastructure/init-creds.sh /tmp/build/ace-server/ace-startup-script.sh
+          cp $PWD/demo-infrastructure/read-hashicorp-creds.sh /tmp/build/ace-server/
+          cp $PWD/demo-infrastructure/read-xml-creds.sh /tmp/build/ace-server/
+          cp tekton/os/cp4i/Dockerfile /tmp/build
+
+      - name: Install docker
+        run: |
+          set -e # Fail on error
+          cd /tmp && curl https://download.docker.com/linux/static/stable/x86_64/docker-27.1.1.tgz | tar -xzvf -
+
+      - name: Login to cp.icr.io
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.CP_USERNAME }}
+          password: ${{ secrets.CP_PASSWORD }}
 
       - name: Create container image
         run: |
@@ -70,3 +97,7 @@ jobs:
           export COMMIT=$(git log -1 --pretty=%h)
           export TAG="$DATE"-"$COMMIT"
           echo Setting container tag to "$TAG"
+          
+          cd /tmp/build
+          chmod -R 777 .
+          /tmp/docker/docker build --file Dockerfile --build-arg BASE_IMAGE=cp.icr.io/cp/appc/ace-server-prod:12.0.12.0-r1-20240417-022324 -t tdolby/experimental:tea-github-action-$TAG .
