Add mqsiprofile

diff --git a/.github/workflows/cp4i-image.yml b/.github/workflows/cp4i-image.yml
--- a/.github/workflows/cp4i-image.yml
+++ b/.github/workflows/cp4i-image.yml
@@ -57,7 +57,11 @@ jobs:
           
       - name: Create the container structure
         run: |
-          set -e # Fail on error
+          echo "Loading ACE profile"
+          export LICENSE=accept
+          set +e # Don't fail on error if the profile has already been loaded
+          . /opt/ibm/ace-12/server/bin/mqsiprofile
+          set -e # Fail on error - this must be done after the profile in case the container has the profile loaded already
           rm -rf /tmp/build
           mkdir -p /tmp/build
           echo ========================================================================
